## NumPy Array Slicing

We pass slice instead of index like this: **[start:end].**
We can also define the step, like this: **[start:end:step].**

Slice elements from index 1 to index 5 from the following array:

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


Slice elements from index 4 to the end of the array:

In [2]:
print(arr[4:])

[5 6 7]


Slice elements from the beginning to index 4 (not included):

In [3]:
print(arr[:4])


[1 2 3 4]


## Negative Slicing

In [4]:
print(arr[-3:-1])


[5 6]


## STEP

In [5]:
print(arr[1:5:2])


[2 4]


In [6]:
print(arr[::2])


[1 3 5 7]


## Slicing 2-D Arrays

In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])


[7 8 9]


In [8]:
print(arr[0:2, 2])


[3 8]


In [9]:
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]
